[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/api"
  to = "https://ulatroi.net/api/"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}